import images from './images'
const shopsName = [
  "Mc Donald's",
  'KFC',
  'Burger King',
  'Evrasia',
  'Mafia',
  'Mister Cat',
]

const shopsGoods = {
  "Mc Donald's": [
    { name: 'Big Mac', price: 50, url: images.BigMac, id: 1, count: 0 },
    { name: 'Big Tasty', price: 60, url: images.BigTasty, id: 2, count: 0 },
    {
      name: 'Cheeseburger',
      price: 45,
      url: images.Cheeseburger,
      id: 3,
      count: 0,
    },
    {
      name: 'Double Cheeseburger',
      price: 50,
      url: images.DoubleCheeseburger,
      id: 4,
      count: 0,
    },
    { name: 'Hamburger', price: 30, url: images.Hamburger, id: 5, count: 0 },
    { name: 'Mc Chicken', price: 50, url: images.McChicken, id: 6, count: 0 },
    {
      name: 'Roll Chicken',
      price: 60,
      url: images.RollChicken,
      id: 7,
      count: 0,
    },
    { name: 'Coca Cola', price: 20, url: images.CocaCola, id: 8, count: 0 },
    { name: 'Fanta', price: 20, url: images.Fanta, id: 9, count: 0 },
    { name: 'Sprite', price: 20, url: images.Sprite, id: 10, count: 0 },
  ],
  KFC: [
    { name: 'Basket-S', price: 50, url: images.BasketS, id: 1, count: 0 },
    {
      name: 'Belgian Waffles',
      price: 20,
      url: images.BelgiysayaVaflya,
      id: 2,
      count: 0,
    },
    { name: 'Hot Dog', price: 20, url: images.hotDog, id: 3, count: 0 },
    {
      name: 'Fries Small',
      price: 50,
      url: images.kartofelFriMini,
      id: 4,
      count: 0,
    },
    {
      name: 'Ice Cream',
      price: 35,
      url: images.morozhenoeRozhok,
      id: 5,
      count: 0,
    },
    {
      name: 'Ice Cream Chocolate',
      price: 45,
      url: images.morozhenoeShokoladnoe,
      id: 6,
      count: 0,
    },
    {
      name: 'Sanders Pita',
      price: 50,
      url: images.pita,
      id: 7,
      count: 0,
    },
    { name: 'Stripsy', price: 30, url: images.stripsy, id: 8, count: 0 },
  ],
  'Burger King': [
    { name: 'Bacon King', price: 50, url: images.baconKing, id: 1, count: 0 },
    {
      name: 'Big King XXL',
      price: 60,
      url: images.bigKingXxl,
      id: 2,
      count: 0,
    },
    {
      name: 'Big King',
      price: 45,
      url: images.bigKing,
      id: 3,
      count: 0,
    },
    {
      name: 'Chicken Salad',
      price: 50,
      url: images.chickenSalad,
      id: 4,
      count: 0,
    },
    {
      name: 'Chicken Tendercrisp',
      price: 30,
      url: images.chickenTendercrisp,
      id: 5,
      count: 0,
    },
    {
      name: 'Chicken Wrap',
      price: 50,
      url: images.chickenWrap,
      id: 6,
      count: 0,
    },
    {
      name: 'Extra Long Chili Cheese',
      price: 60,
      url: images.extraLongChiliCheese,
      id: 7,
      count: 0,
    },
    {
      name: 'Halloumi Salad',
      price: 20,
      url: images.halloumiSalad,
      id: 8,
      count: 0,
    },
    {
      name: 'Long Chicken Cheese',
      price: 20,
      url: images.longChickenCheese,
      id: 9,
      count: 0,
    },
    {
      name: 'Mozzarella Beef',
      price: 20,
      url: images.mozzarellaBeef,
      id: 10,
      count: 0,
    },
    {
      name: 'Mozzarella Chicken',
      price: 20,
      url: images.mozzarellaChicken,
      id: 11,
      count: 0,
    },
    {
      name: 'Whopper Cheese',
      price: 20,
      url: images.whopperCheese,
      id: 12,
      count: 0,
    },
    { name: 'Whopper', price: 20, url: images.whopper, id: 13, count: 0 },
  ],
}

export { shopsName, shopsGoods }
